
spring.data.mongodb.uri=mongodb+srv://1rn21cs130sahil_db_user:BuquJprgfMa36Bjy@meetingdb.wgrenkb.mongodb.net/?appName=meetingdb
spring.data.mongodb.database=meetingdb
server.port=8080
jwt.secret=MyVerySecureJwtSecretKeyForMeetingRoomAPI2026Project